### ISSUE TITLE
Order of tips in `ggtree` plots are not the same as in the generic `plot.phylo` function

### ISSUE THREAD

**Issue by arendsee** [GuangchuangYu/ggtree#157]
The order in which tips are plotted in `ape::plot.phylo` can be set with `ape::rotateConstr`. For example:

``` R
library(ape)
set.seed(42)
x <- rtree(5)
y <- ape::rotateConstr(x, c('t1', 't4', 't5', 't3', 't2'))

# original plot
plot(x)

# plot with reordered tips
plot(y)
```

The documentation of the `rotateConstr` function states that this order should
be followed when plotting the tree. However, `ggtree` plots the tips in the
same order regardless of how they are set:

``` R
library(ggtree)
# both ggtree plots appear the same
ggtree::ggtree(x)
ggtree::ggtree(y)
```

I think it would be good practice for `ggtree` to be consistent with the generic `plot` function.

I am using `ggtree v1.8.2`, `ape 5.0`, and R version 3.4.2

**Comment by brj1** [comment]
Try `ggtree(x, ladderize=F)`.

**Comment by arendsee** [comment]
Ah, you're right. Are all trees with a given topology plotted in the same way in `ggtree`? Are they all internally converted to some canonical form?

**Comment by brj1** [comment]
Not every tree with the same topology is plotted the same. See `z <- ape::rotateConstr(x, c('t1', 't4', 't5', 't2', 't3'))` from your example.

Actually, I'm fiddling with a way to make DensiTree like plots in `ggtree` in my fork of `ggtree`. In order to do so I needed to fix the tip positions. Using:
`ggmultitree(list(x), layout='rectangular', tip.order=c('t1', 't4', 't5', 't3', 't2')) + geom_tiplab()`
in my fork will a similar result as ape.

**Comment by GuangchuangYu** [comment]
@brj1 I would recommend you change the ggmultitree to ggdensitree as the `multitree` may confuse user for the `multiPhylo` object defined in `ape`.

**Comment by GuangchuangYu** [comment]
```r
p1=ggtree(x, ladderize=F) + geom_tiplab()
p2=ggtree(y, ladderize=F) + geom_tiplab()
cowplot::plot_grid(p1, p2, ncol=2)
```

![screenshot 2017-12-06 10 02 38](https://user-images.githubusercontent.com/626539/33640647-a5ab3774-da6c-11e7-988f-e4505cf9851e.png)

**Comment by arendsee** [comment]
@GuangchuangYu Perfect! Thanks
