### ISSUE TITLE
Bug in gplot.heatmap

### ISSUE THREAD

**Issue by mworkentine** [GuangchuangYu/ggtree#3]
Nice package!  I've been looking for something like this for a while.  Noticed a bug in `gplot.heatmap` where the levels of the heatmap aren't reordered properly and the labels don't match up with their respective values in the heatmap.

This line in `gplot.heatmap` simply reorders the label:
```r
levels(dd$Var1) <- df$label[order(df$y)]
```
This correctly reorders the levels:
```r
dd$Var1 <- factor(dd$Var1, levels = df$label[order(df$y)])
```

Also, for very large heatmaps the tree and heatmap don't line up properly.  It would be nice to see if this could be fixed because now it requires manually playing with the plot margins until it looks good.

Example:
```
t = rtree(1000)
data = as.data.frame(replicate(4, rnorm(1000)))
row.names(data) = t$tip.label
gplot(ggtree(t),data)
```

**Comment by GuangchuangYu** [comment]
Good catch and thanks for your report. The reorder issue has been removed in ggtree (version >=0.99.18).

For the line up issue, since that can't be supported internally in current version of ggplot2 (please refer to the Linked micromaps section in [wishlist feature requests](https://github.com/hadley/ggplot2/wiki/wishlist---feature-requests)), gplot will output a list of ggplot2 object and user can manual adjust it if it can align properly.

Of course, I will explore some possibilities to align them more accurately.

**Comment by mworkentine** [comment]
Thanks for the quick fix!

As for the alignment issue I did find that adding `scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0))` to the tree plot allowed for better alignment.

**Comment by GuangchuangYu** [comment]
In devel branch, I have created another function called gheatmap, will will always line up the heatmap to the tree properly.

please refer to the new vignette: http://www.bioconductor.org/packages/3.2/bioc/vignettes/ggtree/inst/doc/ggtree.html
