### ISSUE TITLE
All additional layouts are broken

### ISSUE THREAD

**Issue by uzolotikov** [GuangchuangYu/ggtree#636]
I use 4.4.1 R version and latest ggtree version from BiocManager

Example of the issue:
![{792D69CE-89BF-4A08-B13B-607119ACF2F1}](https://github.com/user-attachments/assets/b708bbbe-474b-466f-91e2-9ea57724253c)

**Comment by uzolotikov** [comment]
Issue fixed with duplicating `layout='YOUR_LAYOUT'` to geom_tree. Action that I couldn't find in any guide... Sure, it's not the expected behavior of ggtree.

**Comment by brj1** [comment]
The issue is that you are not using `ggtree` correctly. The `ggtree` function converts a phylo object (or treedata object) into a tibble using the `ggplot` function and then applies a `geom_tree` layer along with some preporocessing and theme adjustments. This is somewhat equivalent to `ggplot(tree) + geom_tree()`. What you are doing is applying two `geom_tree` layers, one with the 'slanted' layout and other with the 'rect' layout. The correct usage is:

```R
ggtree(tree, layout = 'slanted')
```

**Comment by uzolotikov** [comment]
Thanks!
