### ISSUE TITLE
there is no package called EBImage

### ISSUE THREAD

**Issue by biorelated** [GuangchuangYu/ggtree#65]

**Comment by jsilve24** [comment]
I know this issue is solved by installing [EBImage from bioconductor](http://bioconductor.org/packages/release/bioc/html/EBImage.html). 

But I did want to second that installation of EBImage can be a bottleneck in using ggtree. I have noticed that that particular dependency can cause problems and is difficult to install on some systems.  I haven't looked into how it is used in ggtree or why it seems to be difficult to install though.

**Comment by GuangchuangYu** [comment]
EBImage is used to annotate tree with image, including phylopic, user's images, *etc*.

For installation issue, please refer to <https://github.com/GuangchuangYu/ggtree/wiki/ggtree-installation>.

I may consider to remove the dependency in future. It seems EBImage is not using quite often.

**Comment by GuangchuangYu** [comment]
@jsilve24 FYI, I have removed the dependency of EBImage for ggtree installation.

It is still needed if user want to annotate tree with image file.

But for installation, user don't need to install it.
