### ISSUE TITLE
installation issue - ubuntu

### ISSUE THREAD

**Issue by mahassani** [GuangchuangYu/ggtree#73]
Hello 
I have got this warning message when trying to install ggtree over bioconductor. 
Warning message:
In install.packages(pkgs = doing, lib = lib, ...) :
installation of package ‘ggtree’ had non-zero exit status
A

**Comment by GuangchuangYu** [comment]
you need to post more info.

**Comment by mahassani** [comment]
Which info precisely do you want me to post?

**Comment by GuangchuangYu** [comment]
run R, and in R run 'library("BiocInstaller"); biocLite("ggtree")', then post all the output here if you have no idea of is important.

**Comment by mahassani** [comment]
> biocLite("ggtree")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.3), R 3.2.2 (2015-08-14).
Installing package(s) ‘ggtree’
trying URL 'https://bioconductor.org/packages/3.2/bioc/src/contrib/ggtree_1.2.17.tar.gz'
Content type 'application/x-gzip' length 10275235 bytes (9.8 MB)
==================================================
downloaded 9.8 MB

* installing *source* package ‘ggtree’ ...
** R
** inst
** preparing package for lazy loading
Note: the specification for S3 class “AsIs” in package ‘jsonlite’ seems equivalent to one from package ‘BiocGenerics’: not turning on duplicate class definitions for this class.
Failed with error:  ‘there is no package called ‘EBImage’’
Error in loadNamespace(name) : there is no package called ‘EBImage’
Error : unable to load R code in package ‘ggtree’
ERROR: lazy loading failed for package ‘ggtree’
* removing ‘/usr/local/lib/R/site-library/ggtree’

The downloaded source packages are in
	‘/tmp/RtmpvqcD4F/downloaded_packages’
Warning message:
In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘ggtree’ had non-zero exit status

**Comment by GuangchuangYu** [comment]
First of all,

If you check the badge in <https://github.com/GuangchuangYu/ggtree>, you will find the current release is 1.4.17.

You need to upgrade your R and Bioconductor if you want to install the latest release.

You can of course install the old version, but many features may not be available.

Your issue is due to `EBImage`, you need to install it via `biocLite("EBImage")`.

If you have problem in installing `EBImage`, please check <https://github.com/GuangchuangYu/ggtree/wiki/ggtree-installation>.
