### ISSUE TITLE
limiting zoom 

### ISSUE THREAD

**Issue by TreeT2** [GuangchuangYu/ggtree#81]
Hi Guangchang Yu

I want to zoom into a section of my tree the issue is this clade forms the root to my phylogeny so using gzoom or get_clade_postion also prints all the tree above the node point. Whereas what I want is everything below node x. 

Thanks

**Comment by GuangchuangYu** [comment]
I don't know what you are talking about.

**Comment by TreeT2** [comment]
Im working on a rough phlogeny and so my tree so far looks like:
![rplot](https://cloud.githubusercontent.com/assets/20044679/19637454/1a342796-99c7-11e6-9e57-3728c17fd940.png)

But the clade I want to zoom into is forming the outgroup so if I use [get_clade_position](https://github.com/GuangchuangYu/ggtree/issues/28) I get the the entrie tree back
![rplot01](https://cloud.githubusercontent.com/assets/20044679/19637516/6951aea2-99c7-11e6-9f5a-e1068c6af395.png)

Is there a way to limit the zoom to below a node point? it between to node points?

**Comment by TreeT2** [comment]
Also when a clade has been zoomed in either with get_clade_position or gzoom is it possible to scale it with geom_treescale ? 

Thanks

**Comment by GuangchuangYu** [comment]
why not use `viewClade`?

`geom_treescale` will work with zoom in tree.

**Comment by TreeT2** [comment]
viewClade does the same as get_clade_position, it prints everything above the node. 

geom_treescale doesn't appear to affect the scale of the tree when I use it:
gzoom(tree, 102:143, subtree = F) + geom_treescale(x=2, width = 0.0001)

Also when I use gzoom it slightly changes the topology of the clade. A small group which should be at the top is now in the centre of the phylogeny. 

I have two clades I want to zoom into and I was hoping to use get_clade_position (or viewClade) with geom_hilight to extract the clades and use grid.arrange or plot_grid to form a final figure.

**Comment by GuangchuangYu** [comment]
follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/) and send me a reproducible example

**Comment by GuangchuangYu** [comment]
> viewClade does the same as get_clade_position, it prints everything above the node. 
![screen shot 2016-10-25 at 11 12 09 am](https://cloud.githubusercontent.com/assets/626539/19671795/ead9b71c-9aa3-11e6-8144-3361e76f0beb.png)

those you want to drop (in black) is also belong to the `clade`, this is why `viewClade` show the whole tree.

>geom_treescale doesn't appear to affect the scale of the tree when I use it:
>gzoom(tree, 102:143, subtree = F) + geom_treescale(x=2, width = 0.0001)

1. you can `+geom_treescale()` to `gzoom` output.
2. `x=2` is too large for your tree.

We can access the left panel by `gzoom()[[1]]` and right panel by `gzoom()[[2]]`.
```r
gzoom(tree, 102:143, subtree = F) + geom_treescale(width = 0.0001)
```
will works.

>Also when I use gzoom it slightly changes the topology of the clade. A small group which should be at the top is now in the centre of the phylogeny. 

No. `gzoom` never change the topology. The different is due to `ggtree` plot the tree by [ladderizing](http://treegraph.bioinfweb.info/Help/wiki/Ladderizing) it.

>viewClade and get_clade_position print this with a right side justification

This is due to `viewClade` like `geom_hilight` that adjust `xmin` to `min(x) - branch.length/2`, see the below figure:
![screen shot 2016-10-25 at 11 06 18 am](https://cloud.githubusercontent.com/assets/626539/19671884/9ae26672-9aa4-11e6-8bda-2500652588fe.png)

>I have two clades I want to zoom into and I was hoping to use get_clade_position (or viewClade) with geom_hilight to extract the clades and use grid.arrange or plot_grid to form a final figure.

You can extract the zoom in portion by `gzoom(t, 102:143, subtree = F)[[2]]`, but which color the tree by red and add tiplabels. This may not be what you want.

You can extract the sub-tree and visualize with `ggtree` in the way you want.

```r
library(ape)
subtr <- drop.tip(t, t$tip.label[-c(102:143)], subtree=F)
ggtree(subtr) + geom_tiplab()
```

**Comment by GuangchuangYu** [comment]
why not just use `viewClade` function?
