### ISSUE TITLE
read.raxml() creates extra node with zero branch length

### ISSUE THREAD

**Issue by toddknutson** [GuangchuangYu/ggtree#86]
Hi Guangchuan,

I'm using ggtree version 1.6.1 (GitHub release 3.4), R version 3.3.0. When I read-in a RAxML file (e.g. RAxML_bipartitionsBranchLabels) using the `read.raxml()` function, it generates a tree with an extra node, which seems to be wrong. Using `fortify(raxml_tree)`, I can see that there is an extra row where the node and parent values are the same, and the `branch.length` is 0.00000000. The `isTip` value is `FALSE`.

I was able to see the same problem using your example RAxML file/code:
```
raxml_file <- system.file("extdata/RAxML", "RAxML_bipartitionsBranchLabels.H3", package="ggtree")
raxml <- read.raxml(raxml_file)
```
Then you can see that node 65 also has parent 65:
`fortify(raxml)`

And you can see that the first value of the raxml tree's bootstrap vector is `NA`. 
`raxml@bootstrap`

```
   node bootstrap
1    65        NA
2    66        98
3    67        97
4    68        68
5    69        34
6    70        88
...
```

Is this a bug or do I not understand something? Thanks for your really great `ggtree` package!
-Todd

**Comment by GuangchuangYu** [comment]
This is not a bug. I intended to do this since the output of `fortify()` is node-based. 

The one that have same value of `node` and `parent` is the root node which actually don't have a parent.

If you check the `raxml_file`, you will find that there is no bootstrap value for the `root` node, this is why it's bootstrap value is `NA`.

**Comment by toddknutson** [comment]
OK, now I understand. Thanks!
